#!/bin/bash

audio_libtheora(){
    local pitem_dir=libtheora-1.1.1
    local pitem_file=libtheora-1.1.1.tar.bz2
    local pitem_url="http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2"
    local pitem_target=lib/.libs/libtheora.a
    local pitem_install=$LOCALDIR/lib/libtheora.a

    config_proc(){
        ./configure --prefix=$LOCALDIR --enable-shared=no
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc
}