#!/bin/bash

audio_sox(){
    local pitem_dir=sox-14.4.1
    local pitem_file=sox-14.4.1.tar.gz
    local pitem_url="http://downloads.sourceforge.net/project/sox/sox/14.4.1/sox-14.4.1.tar.gz"
    local pitem_target=src/.libs/libsox.a
    local pitem_install=$LOCALDIR/lib/libsox.a

    config_proc(){
        ./configure --prefix=$LOCALDIR --enable-shared=no
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc
}