#!/bin/bash

proc_libfreetype(){
    local pitem_dir=freetype-2.4.10
    local pitem_file=freetype-2.4.10.tar.gz
    local pitem_url="http://download.savannah.gnu.org/releases/freetype/freetype-2.4.10.tar.gz"
    local pitem_target=objs/.libs/libfreetype.a
    local pitem_install=$GLOBALDIR/lib/libfreetype.a

    config_proc(){
        ./configure --host=$targetHost --prefix=$GLOBALDIR --disable-shared
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc
}