#!/bin/bash

proc_libfribidi(){
    local pitem_dir=fribidi-0.19.4
    local pitem_file=fribidi-0.19.4.tar.bz2
    local pitem_url="https://pkgs.fedoraproject.org/repo/pkgs/fribidi/fribidi-0.19.4.tar.bz2/0173f98ff929782d45819fc4a813c175/fribidi-0.19.4.tar.bz2"
    local pitem_target=lib/.libs/libfribidi.a
    local pitem_install=$GLOBALDIR/lib/libfribidi.a
    do_download_package $package_dir/fribidi.diff https://raw.github.com/jb-alvarado/media-autobuild_suite/master/patches/fribidi.diff

    config_proc(){
        patch -p0 < $package_dir/fribidi.diff
        ./configure --host=$targetHost --prefix=$GLOBALDIR --enable-shared=no
        sed -i 's/-export-symbols-regex "^fribidi_.*" $(am__append_1)/-export-symbols-regex "^fribidi_.*" # $(am__append_1)/g' "lib/Makefile"
    }
    install_proc(){
		make install		

if [ ! -f ${GLOBALDIR}/bin/fribidi-config ]; then
cat > ${GLOBALDIR}/bin/fribidi-config << "EOF"
#!/bin/sh
case $1 in
  --version)
    pkg-config --modversion fribidi
    ;;
  --cflags)
    pkg-config --cflags fribidi
    ;;
  --libs)
    pkg-config --libs fribidi
    ;;
  *)
    false
    ;;
esac
EOF
fi
    }
    do_proc_default do_clean_proc config_proc do_make_proc install_proc
}