#!/bin/bash

proc_gettext(){
    local pitem_dir=gettext-0.18.3.1
    local pitem_file=gettext-0.18.3.1.tar.gz
    local pitem_url="http://ftp.gnu.org/pub/gnu/gettext/gettext-0.18.3.1.tar.gz"
    local pitem_target=gettext-tools/src/xgettext.exe
    local pitem_install=$GLOBALDIR/bin/xgettext.exe

    config_proc(){
        CFLAGS="$CFLAGS -O2" ./configure --host=$targetHost --prefix=$GLOBALDIR --enable-threads=win32 --enable-relocatable --disable-shared LDFLAGS="$LDFLAGS -static -static-libgcc -static-libstdc++ -DPTW32_STATIC_LIB" 
    }
    install_proc(){
        install gettext-tools/src/*.exe $GLOBALDIR/bin
        install gettext-tools/misc/autopoint $GLOBALDIR/bin
    }
    do_proc_default do_clean_proc config_proc do_make_proc install_proc
}