#!/bin/bash

proc_libjpeg(){
    local pitem_dir=jpeg-9
    local pitem_file=jpegsrc.v9.tar.gz
    local pitem_url="http://www.ijg.org/files/jpegsrc.v9.tar.gz"
    local pitem_target=.libs/libjpeg.a
    local pitem_install=$GLOBALDIR/lib/libjpeg.a
    
    config_proc(){
        ./configure --host=$targetHost --prefix=$GLOBALDIR --disable-shared --enable-static
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc
}