#!/bin/bash

proc_libexpat(){
    local pitem_dir=expat-2.1.0
    local pitem_file=expat-2.1.0.tar.gz
    local pitem_url="http://sourceforge.net/projects/expat/files/expat/2.1.0/expat-2.1.0.tar.gz/download"
    local pitem_target=.libs/libexpat.a
    local pitem_install=$GLOBALDIR/lib/libexpat.a

    config_proc(){
        ./configure --host=$targetHost --prefix=$GLOBALDIR --enable-shared=no
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc
}