#!/bin/bash

proc_libgcrypt(){
    local pitem_dir=libgcrypt-1.5.3
    local pitem_file=libgcrypt-1.5.3.tar.bz2
    local pitem_url="ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.5.3.tar.bz2"
    local pitem_target=src/.libs/libgcrypt.a
    local pitem_install=$GLOBALDIR/lib/libgcrypt.a

    config_proc(){
        ./configure --host=$targetHost --prefix=$GLOBALDIR --disable-shared --with-gnu-ld
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc
}