#!/bin/bash

proc_git_libilbc(){
    local pitem_dir=libilbc.git
    local pitem_file=libilbc.git
    local pitem_url="https://github.com/dekkers/libilbc.git"
    local pitem_target=.libs/libilbc.a
    local pitem_install=$GLOBALDIR/lib/libilbc.a

    config_proc(){
        autoreconf -fiv
        ./configure --host=$targetHost --prefix=$GLOBALDIR --disable-shared
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc
}