#!/bin/bash

proc_libpng(){
    local pitem_dir=libpng-1.6.9
    local pitem_file=libpng-1.6.9.tar.gz
    local pitem_url="http://downloads.sourceforge.net/project/libpng/libpng16/1.6.9/libpng-1.6.9.tar.gz"
    local pitem_target=.libs/libpng16.a
    local pitem_install=$GLOBALDIR/lib/libpng.a
    
    config_proc(){
        ./configure --host=$targetHost --prefix=$GLOBALDIR --disable-shared
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc
}