#!/bin/bash

video_git_x264(){
    local pitem_dir=x264.git
    local pitem_file=x264.git
    local pitem_url="http://repo.or.cz/r/x264.git"
    local pitem_target=libx264.a
    local pitem_install=$LOCALDIR/lib/libx264.a

    config_proc(){
        # 8-bit default
         ./configure --host=$targetHost --prefix=$LOCALDIR --extra-cflags=-fno-aggressive-loop-optimizations --enable-static --enable-win32thread
        # 10-bit 
        #./configure --host=$targetHost --prefix=$LOCALDIR --extra-cflags=-fno-aggressive-loop-optimizations --enable-static --enable-win32thread --bit-depth=10
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc

}