#!/bin/bash

video_git_libutvideo(){
    local pitem_dir=libutvideo.git
    local pitem_file=libutvideo.git
    local pitem_url="git://github.com/qyot27/libutvideo.git"
    local pitem_target=utv_core/libutvideo.a
    local pitem_install=$LOCALDIR/lib/libutvideo.a

    do_download_package $package_dir/utv.diff https://raw.github.com/rdp/ffmpeg-windows-build-helpers/master/patches/utv.diff

    config_proc(){
        patch -p0 < $package_dir/utv.diff
        sed -i 's/#define DLLEXPORT __declspec(dllexport)/#define DLLEXPORT/' utv_core/utvideo.h
        sed -i 's/__declspec(dllexport) //' utv_core/GlobalConfig.h
        sed -i 's/__declspec(dllexport) //' utv_core/GlobalConfig.cpp
        ./configure --prefix=$LOCALDIR
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc
}