#!/bin/bash

video_libschroedinger(){
    local pitem_dir=schroedinger-1.0.11
    local pitem_file=schroedinger-1.0.11.tar.gz
    local pitem_url="http://diracvideo.org/download/schroedinger/schroedinger-1.0.11.tar.gz"
    local pitem_target=schroedinger/.libs/libschroedinger-1.0.a
    local pitem_install=$LOCALDIR/lib/libschroedinger-1.0.a

    config_proc(){
        ./configure --host=$targetHost --prefix=$LOCALDIR --disable-shared
        sed -i 's/testsuite//' Makefile
    }
    install_proc(){
        make install
        sed -i 's/-lschroedinger-1.0$/-lschroedinger-1.0 -lorc-0.4/' "$LOCALDIR/lib/pkgconfig/schroedinger-1.0.pc"
    }
    do_proc_default do_clean_proc config_proc do_make_proc install_proc
}