#!/bin/bash

video_frei0r(){
    local pitem_dir=frei0r-plugins-1.4
    local pitem_file=frei0r-plugins-1.4.tar.gz
    local pitem_url="https://files.dyne.org/.xsend.php?file=frei0r/releases/frei0r-plugins-1.4.tar.gz"
    local pitem_target=src/mixer3/RGB/RGB.dll
    local pitem_install=$LOCALDIR/include/frei0r.h

    config_proc(){
        cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=$LOCALDIR .
    }
    do_proc_default do_clean_proc config_proc do_make_proc do_install_proc
}